liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  messenger: true

  webp:
    generate: false

  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%/public'
        cache_prefix: media/cache

  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%/public'

  filter_sets:
    cache: ~

    hero:
      quality: 80
      filters:
        scale:
          dim: [1000, 750]

    miniature:
      quality: 75
      filters:
        scale:
          dim: [400, 300]

    thumb:
      quality: 75
      filters:
        thumbnail: { size: [ 120, 90 ], mode: outbound }

    watermark:
      quality: 80
      filters:
        watermark_image:
          image: assets/Utils/Watermark.png
          size: 0.2
          position: bottomright
        scale:
          dim: [600, 300]

    full_watermark:
      quality: 80
      filters:
        watermark_image:
          image: assets/Utils/Watermark.png
          size: 0.2
          position: bottomright

