twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/form_template.html.twig']
    paths:
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/css': css

when@test:
    twig:
        strict_variables: true
