vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image_gallery:
            uri_prefix: build/images/gallery
            upload_destination: '%kernel.project_dir%/public/build/images/gallery'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
